//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTVAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverInfo
    {
        public DriverInfo()
        {
            this.CarInfo = new HashSet<CarInfo>();
        }
    
        public System.Guid id { get; set; }
        public string DriverName { get; set; }
        public string Age { get; set; }
    
        public virtual ICollection<CarInfo> CarInfo { get; set; }
    }
}
