//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTVAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentOrderItem
    {
        public EquipmentOrderItem()
        {
            this.EquipmentOrderItemDevices = new HashSet<EquipmentOrderItemDevices>();
            this.CarInfo = new HashSet<CarInfo>();
            this.RFID = new HashSet<RFID>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> EquipmentOrderId { get; set; }
        public Nullable<int> BoxNum { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual EquipmentOrder EquipmentOrder { get; set; }
        public virtual ICollection<EquipmentOrderItemDevices> EquipmentOrderItemDevices { get; set; }
        public virtual ICollection<CarInfo> CarInfo { get; set; }
        public virtual ICollection<RFID> RFID { get; set; }
    }
}
