//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTVAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItems
    {
        public string TaskName { get; set; }
        public string TaskNum { get; set; }
        public System.Guid taskId { get; set; }
        public Nullable<int> State { get; set; }
        public System.Guid orderId { get; set; }
        public string TransportNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string DepartName { get; set; }
        public System.Guid orderItemId { get; set; }
        public Nullable<System.Guid> EquipmentOrderId { get; set; }
        public Nullable<int> BoxNum { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public System.Guid boxContentId { get; set; }
        public Nullable<System.Guid> DeviceId { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> deviceNumbers { get; set; }
        public System.Guid RFIDID { get; set; }
        public string EPCNum { get; set; }
        public string EPCName { get; set; }
    }
}
